[package]
name = "ferris-watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
prometheus = "0.13.4"
log = "0.4.22"
env_logger = "0.10"
futures = "0.3"
clap = "3.0"
sysinfo = { version = "0.34.2", features = ["default", "disk", "network"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
ureq = "2.0"
regex = "1.5"
netstat-esr = "0.8.1"
dirs = "5.0.1"
log4rs = "1.2.0"
ribir = { version = "0.3.0"} # Default feature for Ribir
winit = "0.29" # Add winit as a direct dependency
chrono = "0.4"
semver = "1.0" # Add semver crate

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"


[profile.release]
strip = "symbols"
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
