update_service_url:
configuration_service_url:
log_level: info
system_processes:
  - "*WindowServer*"
  - "LM Studio"
  - "Google Chrome*"
  - "*clash-verge*"
  - "*idea*"
detect_docker_processes: false
detect_java_processes: false